language: node_js
node_js:
  - "5"
  - "4"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "iojs"
services:
  - mongodb
before_script:
  - sleep 10
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
script:
  - npm run build
  - npm run test-babel
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
